from enum import Enum

class ErrorCode(str, Enum):
    # 数据层错误 (DATA_*)
    DATA_FETCH_FAILED = "DATA_FETCH_FAILED"
    DATA_SYMBOL_NOT_FOUND = "DATA_SYMBOL_NOT_FOUND"
    DATA_INSUFFICIENT_SAMPLES = "DATA_INSUFFICIENT_SAMPLES"
    DATA_SOURCE_UNAVAILABLE = "DATA_SOURCE_UNAVAILABLE"
    
    # 形态识别错误 (PATTERN_*)
    PATTERN_NOT_FOUND = "PATTERN_NOT_FOUND"
    PATTERN_AMBIGUOUS = "PATTERN_AMBIGUOUS"
    PATTERN_LOGIC_ERROR = "PATTERN_LOGIC_ERROR"
    
    # 系统层错误 (SYSTEM_*)
    SYSTEM_CONFIG_ERROR = "SYSTEM_CONFIG_ERROR"
    SYSTEM_CACHE_ERROR = "SYSTEM_CACHE_ERROR"
    SYSTEM_TIMEOUT = "SYSTEM_TIMEOUT"
    SYSTEM_UNKNOWN = "SYSTEM_UNKNOWN"
    
    # 鉴权/权限 (AUTH_*)
    AUTH_INVALID_API_KEY = "AUTH_INVALID_API_KEY"
    AUTH_QUOTA_EXCEEDED = "AUTH_QUOTA_EXCEEDED"
